### ISSUE TITLE
Import directory of svgs with extract-svg-sprite-webpack-plugin

### ISSUE THREAD

**Issue by joepagan** [JetBrains/svg-mixer#47]
Previously with `svg-sprite-loader`, it was possible to import a directory full of svg files by adding this to an entry point:
```js
const svgFiles = require.context('../svgs', false, /\.svg$/);
svgFiles.keys().forEach(svgFiles);
```
It doesn't appear possible to use this method with `extract-svg-sprite-webpack-plugin`, is this possible?

**Comment by Frezc** [comment]
I also need this function but it throws an error in 0.3.7:
```
TypeError: module.originalSource is not a function
    at Function.replaceInModuleSource (D:\projects\svgTest\node_modules\extract-svg-sprite-webpack-plugin\lib\utils\replacer.js:60:42)
    at sprite.symbols.forEach.s (D:\projects\svgTest\node_modules\extract-svg-sprite-webpack-plugin\lib\plugin.js:122:18)
    at Array.forEach (<anonymous>)
    at result.forEach (D:\projects\svgTest\node_modules\extract-svg-sprite-webpack-plugin\lib\plugin.js:120:22)
    at Array.forEach (<anonymous>)
    at ExtractSvgSpritePlugin.hookAdditionalAssets (D:\projects\svgTest\node_modules\extract-svg-sprite-webpack-plugin\lib\plugin.js:119:12)
    at compileSprites.then.result (D:\projects\svgTest\node_modules\extract-svg-sprite-webpack-plugin\lib\plugin.js:63:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by joepagan** [comment]
@Frezc I believe I got that while trying to just use the plugin normally where I had some SVGs referenced in scss files as `background-image`s. I _think_ the issue was I hadn't got the css loader right, try comment out any `s?css` files imported in your entry point. Though because I don't want that functionality myself, I didn't investigate further.

**Comment by Frezc** [comment]
Ok, if your problem has been solved, feel free to close. I'll create another issue for my problem.

**Comment by joepagan** [comment]
Sorry for the confusion. @Frezc no my problem is not solved, I thought you were referring to a different error.

**Comment by kisenka** [comment]
@joepagan still actual? If yes please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.
